name: trading-bot
services:
- name: trading-bot
  source_dir: /
  github:
    repo: your-github-username/your-repo-name
    branch: main
  run_command: python telegram_bot.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: TELEGRAM_BOT_TOKEN
    value: "${TELEGRAM_BOT_TOKEN}"
    type: SECRET
  - key: STRIPE_SECRET_KEY
    value: "${STRIPE_SECRET_KEY}"
    type: SECRET
  - key: STRIPE_PREMIUM_PRICE_ID
    value: "${STRIPE_PREMIUM_PRICE_ID}"
    type: SECRET
  - key: STRIPE_VIP_PRICE_ID
    value: "${STRIPE_VIP_PRICE_ID}"
    type: SECRET
  - key: DATABASE_URL
    value: "${DATABASE_URL}"
    type: SECRET
  - key: ADMIN_USER_IDS
    value: "7713994326"
  - key: LOG_LEVEL
    value: "INFO"
  - key: HEALTH_CHECK_ENABLED
    value: "true"
  health_check:
    http_path: /health
databases:
- name: trading-db
  engine: PG
  version: "15"
  size: basic
  num_nodes: 1
