#!/bin/bash
# Monitoring Setup Script for Linux/Mac
# Configures monitoring and logging for the trading bot

set -e  # Exit on error

echo "=========================================="
echo "📊 Monitoring Setup Script"
echo "=========================================="
echo ""

# Create logs directory structure
echo "📁 Creating log directories..."
mkdir -p logs/{app,errors,performance,security}
echo "  ✅ Created log directories"

# Install monitoring dependencies
echo ""
echo "📦 Installing monitoring dependencies..."
pip3 install psutil flask requests

# Create monitoring configuration
echo ""
echo "⚙️  Creating monitoring configuration..."

cat > monitoring.env << EOF
# Monitoring Configuration
# Auto-generated by setup_monitoring.sh

# Logging
LOG_LEVEL=INFO
LOG_DIR=logs
LOG_RETENTION_DAYS=30

# Health Check
HEALTH_CHECK_PORT=8080
HEALTH_CHECK_ENABLED=true

# Performance Monitoring
PERFORMANCE_MONITORING_ENABLED=true
METRICS_ENABLED=true

# Alerting
ALERT_EMAIL=
ALERT_WEBHOOK_URL=

# Uptime Monitoring (configure separately)
UPTIME_ROBOT_API_KEY=
EOF

echo "  ✅ Created monitoring.env"

# Create health check monitor script
echo ""
echo "📝 Creating health check monitor script..."

cat > health_check_monitor.sh << 'HEALTHCHECK'
#!/bin/bash
# Health Check Monitor
# Runs health checks and logs results

HEALTH_URL="http://localhost:8080/health"
LOG_FILE="logs/health_checks.log"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

if curl -f -s -o /dev/null -w "%{http_code}" "$HEALTH_URL" > /dev/null 2>&1; then
    echo "[$TIMESTAMP] Health check: OK" >> "$LOG_FILE"
else
    echo "[$TIMESTAMP] Health check: FAILED" >> "$LOG_FILE"
    echo "⚠️  Health check failed!" >&2
fi
HEALTHCHECK

chmod +x health_check_monitor.sh
echo "  ✅ Created health_check_monitor.sh"

# Create systemd service for health checks (optional)
echo ""
echo "📋 To set up automated health checks with systemd:"
echo "   1. Create service file: /etc/systemd/system/trading-bot-healthcheck.service"
echo "   2. Enable and start: sudo systemctl enable --now trading-bot-healthcheck.timer"

# Create systemd timer template
cat > trading-bot-healthcheck.timer << 'TIMER'
[Unit]
Description=Run Trading Bot Health Check
Requires=trading-bot-healthcheck.service

[Timer]
OnCalendar=*:0/5
Persistent=true

[Install]
WantedBy=timers.target
TIMER

cat > trading-bot-healthcheck.service << 'SERVICE'
[Unit]
Description=Trading Bot Health Check
After=network.target

[Service]
Type=oneshot
User=botuser
WorkingDirectory=/home/botuser/trading-bot
ExecStart=/home/botuser/trading-bot/health_check_monitor.sh
SERVICE

echo "  ✅ Created systemd timer and service files"

# Test monitoring
echo ""
echo "🧪 Testing monitoring setup..."
python3 -c "from monitoring import get_logger; logger = get_logger(); print('✅ Monitoring module loaded successfully')"

echo ""
echo "=========================================="
echo "✅ Monitoring Setup Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Configure monitoring.env with your settings"
echo "2. Set up systemd timer for automated health checks (optional)"
echo "3. Configure uptime monitoring (UptimeRobot, etc.)"
echo "4. Set up error alerts (email/webhook)"
echo ""

