# Backup Setup Script for Windows
# Configures automated backups for the trading bot

Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "💾 Backup Setup Script" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

# Create backup directories
Write-Host "📁 Creating backup directories..." -ForegroundColor Cyan
$backupDirs = @("backups", "backups\database", "backups\json", "backups\logs")
foreach ($dir in $backupDirs) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    Write-Host "  ✅ Created $dir" -ForegroundColor Green
}

# Create backup script
Write-Host ""
Write-Host "📝 Creating backup script..." -ForegroundColor Cyan

$backupScript = @"
# Automated Backup Script
# Runs backups and cleans up old files

`$timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
`$backupDir = "backups"
`$retentionDays = 30

Write-Host "[`$timestamp] Starting backup..." -ForegroundColor Cyan

# Backup JSON files
Write-Host "  📦 Backing up JSON files..." -ForegroundColor Yellow
`$jsonFiles = @(
    "users_data.json",
    "trade_history.json",
    "signals_db.json",
    "user_notifications.json",
    "user_profiles.json",
    "community_data.json",
    "referral_data.json",
    "paper_trading.json",
    "sentiment_data.json",
    "broker_connections.json"
)

`$jsonBackupDir = Join-Path `$backupDir "json"
`$jsonBackupFile = Join-Path `$jsonBackupDir "json_backup_`$timestamp.zip"

`$jsonFilesToBackup = `$jsonFiles | Where-Object { Test-Path `$_ }
if (`$jsonFilesToBackup.Count -gt 0) {
    Compress-Archive -Path `$jsonFilesToBackup -DestinationPath `$jsonBackupFile -Force
    Write-Host "    ✅ Created: `$jsonBackupFile" -ForegroundColor Green
} else {
    Write-Host "    ⚠️  No JSON files found to backup" -ForegroundColor Yellow
}

# Backup database (if DATABASE_URL is set)
`$dbUrl = `$env:DATABASE_URL
if (`$dbUrl) {
    Write-Host "  🗄️  Backing up database..." -ForegroundColor Yellow
    python backup_system.py backup
} else {
    Write-Host "  ⚠️  DATABASE_URL not set, skipping database backup" -ForegroundColor Yellow
}

# Clean up old backups
Write-Host "  🗑️  Cleaning up old backups..." -ForegroundColor Yellow
`$cutoffDate = (Get-Date).AddDays(-`$retentionDays)

Get-ChildItem -Path `$backupDir -Recurse -File | Where-Object {
    `$_.LastWriteTime -lt `$cutoffDate
} | ForEach-Object {
    Write-Host "    🗑️  Deleting: `$(`$_.Name)" -ForegroundColor Gray
    Remove-Item `$_.FullName -Force
}

Write-Host "[`$timestamp] Backup complete!" -ForegroundColor Green
"@

$backupScript | Out-File -FilePath "run_backup.ps1" -Encoding UTF8
Write-Host "  ✅ Created run_backup.ps1" -ForegroundColor Green

# Create backup configuration
Write-Host ""
Write-Host "⚙️  Creating backup configuration..." -ForegroundColor Cyan

$backupConfig = @"
# Backup Configuration
# Auto-generated by setup_backups.ps1

# Backup Settings
BACKUP_ENABLED=true
BACKUP_RETENTION_DAYS=30
BACKUP_DIR=backups

# Database Backup
DATABASE_BACKUP_ENABLED=true
DATABASE_BACKUP_FORMAT=custom

# JSON Files Backup
JSON_BACKUP_ENABLED=true

# Cloud Storage (optional)
CLOUD_BACKUP_ENABLED=false
AWS_S3_BUCKET=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=

# Email Notifications
BACKUP_NOTIFICATION_EMAIL=
BACKUP_NOTIFICATION_ON_ERROR=true
"@

$backupConfig | Out-File -FilePath "backup_config.env" -Encoding UTF8
Write-Host "  ✅ Created backup_config.env" -ForegroundColor Green

# Test backup system
Write-Host ""
Write-Host "🧪 Testing backup system..." -ForegroundColor Cyan
python -c "from backup_system import BackupManager; print('✅ Backup system module loaded successfully')"

# Instructions for setting up scheduled backups
Write-Host ""
Write-Host "📋 To set up automated backups:" -ForegroundColor Yellow
Write-Host "   1. Open Task Scheduler (taskschd.msc)" -ForegroundColor White
Write-Host "   2. Create Basic Task" -ForegroundColor White
Write-Host "   3. Name: Trading Bot Daily Backup" -ForegroundColor White
Write-Host "   4. Trigger: Daily at 2:00 AM" -ForegroundColor White
Write-Host "   5. Action: Start a program" -ForegroundColor White
Write-Host "   6. Program: powershell.exe" -ForegroundColor White
Write-Host "   7. Arguments: -File `"$(Join-Path $PSScriptRoot "run_backup.ps1")`"" -ForegroundColor White

# Run initial backup
Write-Host ""
$runInitialBackup = Read-Host "Run initial backup now? (y/n)"
if ($runInitialBackup -eq "y" -or $runInitialBackup -eq "Y") {
    Write-Host "🔄 Running initial backup..." -ForegroundColor Cyan
    & ".\run_backup.ps1"
}

Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "✅ Backup Setup Complete!" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Configure backup_config.env with your settings" -ForegroundColor White
Write-Host "2. Set up Task Scheduler for automated daily backups" -ForegroundColor White
Write-Host "3. Configure cloud storage backup (optional)" -ForegroundColor White
Write-Host "4. Test restore procedure: python backup_system.py restore <backup_file>" -ForegroundColor White
Write-Host ""

