# Monitoring Setup Script for Windows
# Configures monitoring and logging for the trading bot

Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "📊 Monitoring Setup Script" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

# Create logs directory structure
Write-Host "📁 Creating log directories..." -ForegroundColor Cyan
$logDirs = @("logs", "logs\app", "logs\errors", "logs\performance", "logs\security")
foreach ($dir in $logDirs) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    Write-Host "  ✅ Created $dir" -ForegroundColor Green
}

# Install monitoring dependencies
Write-Host ""
Write-Host "📦 Installing monitoring dependencies..." -ForegroundColor Cyan
pip install psutil flask requests

# Create monitoring configuration
Write-Host ""
Write-Host "⚙️  Creating monitoring configuration..." -ForegroundColor Cyan

$monitoringConfig = @"
# Monitoring Configuration
# Auto-generated by setup_monitoring.ps1

# Logging
LOG_LEVEL=INFO
LOG_DIR=logs
LOG_RETENTION_DAYS=30

# Health Check
HEALTH_CHECK_PORT=8080
HEALTH_CHECK_ENABLED=true

# Performance Monitoring
PERFORMANCE_MONITORING_ENABLED=true
METRICS_ENABLED=true

# Alerting
ALERT_EMAIL=
ALERT_WEBHOOK_URL=

# Uptime Monitoring (configure separately)
UPTIME_ROBOT_API_KEY=
"@

$monitoringConfig | Out-File -FilePath "monitoring.env" -Encoding UTF8
Write-Host "  ✅ Created monitoring.env" -ForegroundColor Green

# Create scheduled task for health checks (Windows Task Scheduler)
Write-Host ""
Write-Host "⏰ Setting up scheduled health checks..." -ForegroundColor Cyan

$taskName = "TradingBotHealthCheck"
$scriptPath = Join-Path $PSScriptRoot "health_check_monitor.ps1"

# Create health check monitor script
$healthCheckScript = @"
# Health Check Monitor
# Runs health checks and logs results

`$healthUrl = "http://localhost:8080/health"
`$logFile = "logs\health_checks.log"

try {
    `$response = Invoke-WebRequest -Uri `$healthUrl -TimeoutSec 5 -ErrorAction Stop
    `$status = `$response.StatusCode
    `$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content -Path `$logFile -Value "[`$timestamp] Health check: OK (Status: `$status)"
} catch {
    `$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    `$errorMsg = `$_.Exception.Message
    Add-Content -Path `$logFile -Value "[`$timestamp] Health check: FAILED - `$errorMsg"
    
    # Send alert (configure email/webhook here)
    Write-Host "⚠️  Health check failed!" -ForegroundColor Red
}
"@

$healthCheckScript | Out-File -FilePath "health_check_monitor.ps1" -Encoding UTF8
Write-Host "  ✅ Created health_check_monitor.ps1" -ForegroundColor Green

# Instructions for setting up Task Scheduler
Write-Host ""
Write-Host "📋 To set up automated health checks:" -ForegroundColor Yellow
Write-Host "   1. Open Task Scheduler (taskschd.msc)" -ForegroundColor White
Write-Host "   2. Create Basic Task" -ForegroundColor White
Write-Host "   3. Name: Trading Bot Health Check" -ForegroundColor White
Write-Host "   4. Trigger: Every 5 minutes" -ForegroundColor White
Write-Host "   5. Action: Start a program" -ForegroundColor White
Write-Host "   6. Program: powershell.exe" -ForegroundColor White
Write-Host "   7. Arguments: -File `"$scriptPath`"" -ForegroundColor White

# Test monitoring
Write-Host ""
Write-Host "🧪 Testing monitoring setup..." -ForegroundColor Cyan
python -c "from monitoring import get_logger; logger = get_logger(); print('✅ Monitoring module loaded successfully')"

Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "✅ Monitoring Setup Complete!" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Configure monitoring.env with your settings" -ForegroundColor White
Write-Host "2. Set up Task Scheduler for automated health checks" -ForegroundColor White
Write-Host "3. Configure uptime monitoring (UptimeRobot, etc.)" -ForegroundColor White
Write-Host "4. Set up error alerts (email/webhook)" -ForegroundColor White
Write-Host ""

