#!/bin/bash
# Backup Setup Script for Linux/Mac
# Configures automated backups for the trading bot

set -e  # Exit on error

echo "=========================================="
echo "💾 Backup Setup Script"
echo "=========================================="
echo ""

# Create backup directories
echo "📁 Creating backup directories..."
mkdir -p backups/{database,json,logs}
echo "  ✅ Created backup directories"

# Create backup script
echo ""
echo "📝 Creating backup script..."

cat > run_backup.sh << 'BACKUPSCRIPT'
#!/bin/bash
# Automated Backup Script
# Runs backups and cleans up old files

TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
BACKUP_DIR="backups"
RETENTION_DAYS=30

echo "[$TIMESTAMP] Starting backup..."

# Backup JSON files
echo "  📦 Backing up JSON files..."
JSON_FILES=(
    "users_data.json"
    "trade_history.json"
    "signals_db.json"
    "user_notifications.json"
    "user_profiles.json"
    "community_data.json"
    "referral_data.json"
    "paper_trading.json"
    "sentiment_data.json"
    "broker_connections.json"
)

JSON_BACKUP_DIR="$BACKUP_DIR/json"
JSON_BACKUP_FILE="$JSON_BACKUP_DIR/json_backup_$TIMESTAMP.tar.gz"

FILES_TO_BACKUP=()
for file in "${JSON_FILES[@]}"; do
    if [ -f "$file" ]; then
        FILES_TO_BACKUP+=("$file")
    fi
done

if [ ${#FILES_TO_BACKUP[@]} -gt 0 ]; then
    tar -czf "$JSON_BACKUP_FILE" "${FILES_TO_BACKUP[@]}"
    echo "    ✅ Created: $JSON_BACKUP_FILE"
else
    echo "    ⚠️  No JSON files found to backup"
fi

# Backup database (if DATABASE_URL is set)
if [ -n "$DATABASE_URL" ]; then
    echo "  🗄️  Backing up database..."
    python3 backup_system.py backup
else
    echo "  ⚠️  DATABASE_URL not set, skipping database backup"
fi

# Clean up old backups
echo "  🗑️  Cleaning up old backups..."
find "$BACKUP_DIR" -type f -mtime +$RETENTION_DAYS -delete
echo "    ✅ Cleaned up backups older than $RETENTION_DAYS days"

echo "[$TIMESTAMP] Backup complete!"
BACKUPSCRIPT

chmod +x run_backup.sh
echo "  ✅ Created run_backup.sh"

# Create backup configuration
echo ""
echo "⚙️  Creating backup configuration..."

cat > backup_config.env << EOF
# Backup Configuration
# Auto-generated by setup_backups.sh

# Backup Settings
BACKUP_ENABLED=true
BACKUP_RETENTION_DAYS=30
BACKUP_DIR=backups

# Database Backup
DATABASE_BACKUP_ENABLED=true
DATABASE_BACKUP_FORMAT=custom

# JSON Files Backup
JSON_BACKUP_ENABLED=true

# Cloud Storage (optional)
CLOUD_BACKUP_ENABLED=false
AWS_S3_BUCKET=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=

# Email Notifications
BACKUP_NOTIFICATION_EMAIL=
BACKUP_NOTIFICATION_ON_ERROR=true
EOF

echo "  ✅ Created backup_config.env"

# Create systemd timer for automated backups
echo ""
echo "📋 Creating systemd timer for automated backups..."

cat > trading-bot-backup.timer << 'TIMER'
[Unit]
Description=Run Trading Bot Daily Backup
Requires=trading-bot-backup.service

[Timer]
OnCalendar=daily
OnCalendar=02:00
Persistent=true

[Install]
WantedBy=timers.target
TIMER

cat > trading-bot-backup.service << 'SERVICE'
[Unit]
Description=Trading Bot Daily Backup
After=network.target

[Service]
Type=oneshot
User=botuser
WorkingDirectory=/home/botuser/trading-bot
Environment="PATH=/home/botuser/trading-bot/venv/bin"
ExecStart=/home/botuser/trading-bot/run_backup.sh
SERVICE

echo "  ✅ Created systemd timer and service files"

# Test backup system
echo ""
echo "🧪 Testing backup system..."
python3 -c "from backup_system import BackupManager; print('✅ Backup system module loaded successfully')"

# Instructions
echo ""
echo "📋 To set up automated backups:"
echo "   1. Copy timer and service files to /etc/systemd/system/"
echo "   2. Enable timer: sudo systemctl enable --now trading-bot-backup.timer"
echo "   3. Check status: sudo systemctl status trading-bot-backup.timer"

# Run initial backup
echo ""
read -p "Run initial backup now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "🔄 Running initial backup..."
    ./run_backup.sh
fi

echo ""
echo "=========================================="
echo "✅ Backup Setup Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Configure backup_config.env with your settings"
echo "2. Set up systemd timer for automated daily backups"
echo "3. Configure cloud storage backup (optional)"
echo "4. Test restore procedure: python3 backup_system.py restore <backup_file>"
echo ""

